### ISSUE TITLE
Can't install the lib with cocoapods

### ISSUE THREAD

**Issue by jpapay** [espresso3389/oauth2_custom_uri_scheme#1]
Hello, I'm facing this issue when i'm trying to compile my project : 

<img width="1932" alt="Screenshot at Sep 25 14-50-28" src="https://user-images.githubusercontent.com/15807770/65602316-faafcf80-dfa3-11e9-9739-9727f240fa61.png">

Flutter 1.9.1+hotfix.2 and XCode 11

**Comment by espresso3389** [comment]
This is almost a FAQ. See [the comment](https://github.com/flutter/flutter/issues/25676#issuecomment-449543241) for the resolution.
