### ISSUE TITLE
Can you provide concrete example that works?

### ISSUE THREAD

**Issue by allenind** [espresso3389/oauth2_custom_uri_scheme#2]
Hello, I found your package on pub.dev and would love to implement this on fitbit API. However I do not understand your documentation and the example you provided does not work. Would love to hear back from you ASAP! Thanks

**Comment by espresso3389** [comment]
Based on [Accessing the Fitbit API](https://dev.fitbit.com/build/reference/web-api/oauth2/) page, the basic configuration should be like the following fragment:

```dart
final oauth2Config = OAuth2Config(
  uniqueId: 'www.fitbit.com#1', // any arbitrary value
  authorizationEndpoint: Uri.parse('https://www.fitbit.com/oauth2/authorize'),
  tokenEndpoint: Uri.parse('https://www.fitbit.com/oauth2/authorize/token'),
  revocationEndpoint: Uri.parse('https://www.fitbit.com/oauth2/authorize/revoke'),
  // NOTE: For Android, we also have corresponding intent-filter entry on example/android/app/src/main/AndroidManifest.xml
  redirectUri: Uri.parse('YOUR_APP_SCHEME://callback'), // Your callback URI
  clientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Your Fitbit client ID
  clientSecret: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy', // Your Fitbit client secret
  useBasicAuth: true);
```

Please show me more about your problem and/or your code; "does not work" does not provide any information.

**Comment by allenind** [comment]
I am unsure as to what the redirect Uri should be. Should it be any arbitrary value just so when my user authenticates he/she is redirected to my application?

**Comment by espresso3389** [comment]
Redirect URI plays very crucial role on OAuth2. As noted on the fragment above, you should update your app's [AndroidManifest.xml](https://github.com/espresso3389/oauth2_custom_uri_scheme/blob/master/example/android/app/src/main/AndroidManifest.xml#L31) to have the identical redirect URI (and of course it must be identical to the one registered with your app on Fitbit site; see [Redirect URIs - dev.fitbit.com](https://dev.fitbit.com/build/reference/web-api/oauth2/#redirect-uris)). It must be unique to your app but any arbitrary app scheme can be used.

The plugin does almost everything but it's your own task to define your own redirect URI.

**Comment by allenind** [comment]
Hmm, looks like I cannot use this pacakage with the Fitbit API because of improper Auth call. I'll try to use this with another API I hope to use. I'll maybe just send you a message about it? The error I'm getting is this: 
![image](https://user-images.githubusercontent.com/47741578/68071683-b3450c00-fdb7-11e9-80dc-9a77b24f8746.png)

My code is this 
`import 'package:oauth2_custom_uri_scheme/oauth2_custom_uri_scheme.dart';
import 'package:oauth2_custom_uri_scheme/oauth2_token_holder.dart';

import 'package:flutter/material.dart';

//
// OAuth2Config can be app global to keep the OAuth configuration
//
final oauth2Config = OAuth2Config(
  uniqueId: 'www.fitbit.com#1', // NOTE: ID to identify the credential for box session
  authorizationEndpoint: Uri.parse('https://www.fitbit.com/oauth2/authorize'),
  tokenEndpoint: Uri.parse('https://api.fitbit.com/oauth2/token'),
  scope: 'activity',
  // revocationEndpoint is optional
  // NOTE: For Android, we also have corresponding intent-filter entry on example/android/app/src/main/AndroidManifest.xml
  redirectUri: Uri.parse('https://thesis-1563517235656.firebaseapp.com/__/auth/handler://callback'),
  clientId: 'XXXX',
  clientSecret: 'XXXXXXXXX',
  useBasicAuth: true);

class Testingg extends StatelessWidget {
  @override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: Text('Simple OAuth Sample'),
    ),
    body: Center(
      // OAuth2TokenHolder is the easiest way to create [authorize] button.
      child: OAuth2TokenHolder(
        config: oauth2Config,
        builder: (context, accessToken, state, authorize, deauthorize, child) => ListTile(title: RaisedButton(
          onPressed:() => accessToken == null ? authorize() : deauthorize(),
          child: state == OAuth2TokenAvailability.Authorizing
          ? const CircularProgressIndicator()
          : Text(accessToken == null ? 'Authorize' : 'Deauthorize'))
        )
      )
    )
  );
}

}



testing() async{

// After [Authorize] on the UI, we can get the access token from cache.
AccessToken token = await oauth2Config.getAccessTokenFromCache();

// Or, of course, you can authorize the app
// If reset=false, it may use the cache and the method returns immediately;
// otherwise reset=true, it always tries to authorize the app.
token = await oauth2Config.authorize(reset: true);

// OK, we can execute GET query
//final foobarResult = await token.getJsonFromUri('https://example.com/api/2.0/foobar');
print(token);
}
`

**Comment by espresso3389** [comment]
The redirect URI on your code is completely wrong. It should be an URI with custom URI scheme.

If you register your app with such callback URI:

![image](https://user-images.githubusercontent.com/1311400/68071759-040d3280-fdc1-11e9-860f-fa6dfc2fc4b8.png)

Then your code should have `redirectUri` like the following one:

```dart
redirectUri: Uri.parse('something-unique-app-scheme://callback')
```

And your android manifest should have:

```xml
<intent-filter>
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="something-unique-app-scheme" android:host="callback" />
</intent-filter>
```

**Comment by allenind** [comment]
Sorry I'm really unsure what the redirect uri is since I just copied it form firebase authentication providers 
![image](https://user-images.githubusercontent.com/47741578/68071886-2e0f2680-fdba-11e9-9d0e-f62da6ebab9a.png) Thank you for sharing that information to me. Here is what the screen displays now that ive editted that one out. 
![image](https://user-images.githubusercontent.com/47741578/68072051-47b16d80-fdbc-11e9-8143-82e5566df471.png) Idk why it doesn't work, it works with my facebook login. How can I setup my own redirectURI even if I dont have a server?

**Comment by espresso3389** [comment]
You told me that you're using Fitbit API, so the redirect URI must be the one configured on Fitbit's website. It has nothing to do with Firebase.

Did you register yourself on Fitbit's developer site?
You should register:
- yourself as a Fitbit developer
- a new client app

**Comment by allenind** [comment]
Yes I did all those things but the redirect URI was copied from firebase since I planned to go serverless for this project, and that lead me to use Firebase as a backend provider. I'm kinda lost with all these API's given that I am a new to flutter and to using API's. I really appreciate your help. Thank you so much

**Comment by espresso3389** [comment]
Once again, it has nothing to do with Firebase, nothing to do with serverless.

It's truely just a configuration of your app. Please use the callback URL registered with Fitbit developer website.
