### ISSUE TITLE
Refresh token and API requests

### ISSUE THREAD

**Issue by Tobi3030** [espresso3389/oauth2_custom_uri_scheme#6]
Hello,

I use the package to access the [trakt.tv API](https://trakt.docs.apiary.io/#reference/authentication-oauth). With the help of the provided example I managed to authorize and also to revoke access.
For further use I have two questions:
1. How can I use a refresh token to get a new access token?
2. Where is the access token stored and how can I use it to send requests to the API?

Thank you for your help.

**Comment by espresso3389** [comment]
[AccessToken](https://pub.dev/documentation/oauth2_custom_uri_scheme/latest/oauth2_custom_uri_scheme/AccessToken-class.html) has two methods, [refresh](https://pub.dev/documentation/oauth2_custom_uri_scheme/latest/oauth2_custom_uri_scheme/AccessToken/refresh.html) and [refreshIfNeede](https://pub.dev/documentation/oauth2_custom_uri_scheme/latest/oauth2_custom_uri_scheme/AccessToken/refreshIfNeeded.html) for refreshing access token.

And, you can get the access token string by [accessToken](https://pub.dev/documentation/oauth2_custom_uri_scheme/latest/oauth2_custom_uri_scheme/AccessToken/accessToken.html).

The class also equips several wrapper specialized for common use. But you can of course create your http request by your hand.

**Comment by Tiger3030** [comment]
Thank you for your fast answer.
I used the following code for authorization:

`import 'package:flutter/material.dart';
import 'package:oauth2_custom_uri_scheme/oauth2_custom_uri_scheme.dart';
import 'package:oauth2_custom_uri_scheme/oauth2_token_holder.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Simple OAuth Sample',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

final oauth2Config = OAuth2Config(
    uniqueId: 'trakt', // NOTE: ID to identify the credential save
    authorizationEndpoint: Uri.parse('https://trakt.tv/oauth/authorize'),
    tokenEndpoint: Uri.parse('https://api.trakt.tv/oauth/token'),
    // revocationEndpoint is optional
    revocationEndpoint: Uri.parse('https://api.trakt.tv/oauth/revoke'),
    // NOTE: For Android, we also have corresponding intent-filter entry on example/android/app/src/main/AndroidManifest.xml
    redirectUri: Uri.parse('...'),
    clientId:
        '...',
    clientSecret:
        '...',
    //scope: 'user.read',
    useBasicAuth: false);

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Simple Azure AD OAuth2.0 Example'),
        ),
        body: Center(
            child: OAuth2TokenHolder(
                config: oauth2Config,
                builder: (context, accessToken, state, authorize, deauthorize,
                        child) =>
                    ListTile(
                        title: RaisedButton(
                            onPressed: () => accessToken == null
                                ? authorize()
                                : deauthroizeConfirm(deauthorize),
                            child: state == OAuth2TokenAvailability.Authorizing
                                ? const CircularProgressIndicator()
                                : Text(accessToken == null
                                    ? 'Authorize'
                                    : 'Deauthorize'))))));
  }

  /// NOTE: it's your app's responsibility to interact with the user; the deauthorize function does not interact with him/her.
  Future<bool> deauthroizeConfirm(void deauthorize()) async {
    final ret = await showDialog<bool>(
        context: context,
        builder: (context) => AlertDialog(
                title: Text('Deauthorize App'),
                content: Text('Do you really want to deauthorize the app?'),
                actions: <Widget>[
                  FlatButton(
                      child: Text("Cancel"),
                      onPressed: () => Navigator.of(context).pop(false)),
                  FlatButton(
                      child: Text("Deauthorize"),
                      onPressed: () => Navigator.of(context).pop(true))
                ]));
    if (ret) {
      deauthorize();
    }
    return ret;
  }
}`

To save the token I need to use the saveToken method, right? What code do I need to add for that?

**Comment by Tiger3030** [comment]
Thank you for your fast answer.
Can you please give me an example for the use of the createRequest method?
I want to send a request with custom headers and URI parameters and assign the response to a variable. If needed the token should be refreshed.
