### ISSUE TITLE
Error: Unhandled Exception: Invalid argument(s)

### ISSUE THREAD

**Issue by Tobi3030** [espresso3389/oauth2_custom_uri_scheme#7]
Hello,

in the following code I get an error when calling the function "token":
```
Future<AccessToken> getToken() async {
    final response =
        await AccessTokenStore.fromId('id').getSavedToken(id: null);
    return response;
  }

  Future<void> token() async {
    AccessToken test = await getToken();
    String token = test.accessToken;
  } 
```

This is the error:
`E/flutter (24631): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s)
E/flutter (24631): #0      _StringBase.+ (dart:core-patch/string_patch.dart:265:57)
E/flutter (24631): #1      AccessTokenStore.getSavedToken (package:oauth2_custom_uri_scheme/oauth2_custom_uri_scheme.dart:370:72)
E/flutter (24631): #2      _LoginState.getToken (package:seriesort/login.dart:30:48)
E/flutter (24631): #3      _LoginState.token (package:seriesort/login.dart:35:30)
E/flutter (24631): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (24631): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (24631): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (24631): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (24631): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (24631): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (24631): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (24631): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (24631): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (24631): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (24631): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (24631): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (24631): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (24631): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (24631): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (24631): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (24631): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (24631): #21     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (24631): #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (24631): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (24631): #24     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (24631): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (24631): `

What do I do wrong?

**Comment by espresso3389** [comment]
`getSavedToken` does not accept `null`. It should have valid ID that was used with `saveToken` call.
Normally, it is [OAuth2Config.uniqueId](https://pub.dev/documentation/oauth2_custom_uri_scheme/latest/oauth2_custom_uri_scheme/OAuth2Config/uniqueId.html) or `idForCache` of [AccessToken.authorize](https://pub.dev/documentation/oauth2_custom_uri_scheme/latest/oauth2_custom_uri_scheme/AccessToken/authorize.html) call.

**Comment by Tobi3030** [comment]
Thank you for your fast answer. It is working now.
