### ISSUE TITLE
Exception: _updateToken failed: invalid_request: Invalid code_verifier parameter. Server does not support pkce.

### ISSUE THREAD

**Issue by Tobi3030** [espresso3389/oauth2_custom_uri_scheme#8]
Since yesterday I get the following exception when trying to authorize:
`Exception: _updateToken failed: invalid_request: Invalid code_verifier parameter. Server does not support pkce.`

What is the reason for this exception?

**Comment by espresso3389** [comment]
Wow, the server does not support PKCE but it detects PKCE related parameter and returns error... So funny.
We need some extra option not to add code_verifier on token endpoint.

**Comment by espresso3389** [comment]
0.4.7 supports `usePkce` parameter on `OAuth2Config` and `AccessToken.authroize`. Please set `usePkce: false` on your code. I hope it fixes your issue.

**Comment by Tobi3030** [comment]
Thank you very much, this fixed my issue.
